export const UPDATE_SLIDER = 'UPDATE_SLIDER';  
export const CHANNEL_DRAG_START = 'CHANNEL_DRAG_START';  
export const CHANNEL_DRAG_STOP = 'CHANNEL_DRAG_STOP';  

export const UPDATE_CATEGORY_SLIDER = 'UPDATE_CATEGORY_SLIDER';  
  